/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.helper.jsonc --include-runtime=false --strict-vars=false --env-interface=HelperLedgerEnv src/helper-ledger-configuration.d.ts` (hash: 5d58d070644ccf9f2921e2fe70deb19f)
interface __BaseEnv_HelperLedgerEnv {
	HELPER_LEDGER_ENABLED: string;
	HELPER_LEDGER_POLICY: string;
	HELPER_LEDGER_TOKEN: string;
	HELPER_LEDGER: DurableObjectNamespace<import("./helper-ledger-worker").HelperSpendingLedger>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./helper-ledger-worker");
		durableNamespaces: "HelperSpendingLedger";
	}
	interface Env extends __BaseEnv_HelperLedgerEnv {}
}
interface HelperLedgerEnv extends __BaseEnv_HelperLedgerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "HELPER_LEDGER_ENABLED" | "HELPER_LEDGER_POLICY" | "HELPER_LEDGER_TOKEN">> {}
}
